In [3]:
import numpy as np

In [1]:
import sys

In [15]:
list= range(100)

arr = np.arange(100)


In [10]:
print(sys.getsizeof(23)* len(list))

2800


In [16]:
arr.itemsize

4

In [17]:
import time

In [20]:
x= range(100000)
y= range(100000,200000)
start_time= time.time()
c= [ x+y for x,y in zip(x,y)]
print(time.time()-start_time)

0.009006738662719727


In [35]:
arr2 = np.arange(24).reshape(6,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
arr2.ndim

2

In [30]:
arr3 = np.arange(24)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
arr.ndim

1

In [38]:
arr2 = np.arange(24).reshape(6,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
arr2[0:3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
arr2[2:3]

array([[ 8,  9, 10, 11]])

In [47]:
arr2[:,3:]

array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]])

In [52]:
arr2[3:5,:3]

array([[13, 14],
       [17, 18]])

In [53]:
arr2[1:3,0:3]

array([[ 4,  5,  6],
       [ 8,  9, 10]])

In [57]:
arr2[1:2,2:3]

array([[6]])

In [55]:
for i in arr2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]
